### ISSUE TITLE
Linter crashing (TypeError: Cannot read property 'column' of null)

### ISSUE THREAD

**Issue by SamuelTroper** [spadarian/docblock-python#37]
Getting an issue when using the linter. Happy to help debug - below is my console output:

```
C:\Users\Samuel Troper\.atom\packages\linter\lib\linter-registry.js:154 [Linter] Error running docblock-python TypeError: Cannot read property 'column' of null
    at Object.get_init (file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/docblock-python.js:575:22)
    at Object.get_class_init (file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/linter-docblock-python.js:83:27)
    at file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/linter-docblock-python.js:164:33
    at Array.map (<anonymous>)
    at file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/linter-docblock-python.js:162:17
    at file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/linter-docblock-python.js:176:10
    at Object.lint_docblocks (file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/linter-docblock-python.js:178:38)
    at file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/docblock-python.js:176:22
    at new Promise (<anonymous>)
    at Object.lint (file:///C:/Users/Samuel Troper/.atom/packages/docblock-python/lib/docblock-python.js:175:14)
    at file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/linter-registry.js:113:26
    at new Promise (<anonymous>)
    at _loop (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/linter-registry.js:111:9)
    at LinterRegistry.<anonymous> (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/linter-registry.js:98:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/linter-registry.js:178:4)
    at Generator.next (<anonymous>)
    at step (C:\Users\Samuel Troper\.atom\packages\linter\lib\linter-registry.js:9:273)
    at C:\Users\Samuel Troper\.atom\packages\linter\lib\linter-registry.js:9:443
    at new Promise (<anonymous>)
    at LinterRegistry.<anonymous> (C:\Users\Samuel Troper\.atom\packages\linter\lib\linter-registry.js:9:99)
    at file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/main.js:114:30
    at Function.simpleDispatch (C:\Users\Samuel Troper\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1209208)
    at Emitter.emit (C:\Users\Samuel Troper\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1210649)
    at EditorLinter.lint (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/editor-linter.js:52:18)
    at EditorRegistry.createFromTextEditor (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/editor-registry.js:47:20)
    at file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/editor-registry.js:28:14
    at Workspace.observeTextEditors (C:\Users\Samuel Troper\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:428138)
    at EditorRegistry.activate (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/editor-registry.js:27:22)
    at Linter.registryEditorsInit (file:///C:/Users/Samuel Troper/.atom/packages/linter/lib/main.js:124:26)
(anonymous) @ C:\Users\Samuel Troper\.atom\packages\linter\lib\linter-registry.js:154
```

**Comment by spadarian** [comment]
Do you mind sending a minimal version of the function/class definition?
