### ISSUE TITLE
[Linter] Error running docblock-python

### ISSUE THREAD

**Issue by samamorgan** [spadarian/docblock-python#40]
If the experimental Lint support is enabled, I receive the titled error from Linter. Screenshot:

![image](https://user-images.githubusercontent.com/356814/69570804-72cf4d00-0f75-11ea-80bd-b8377f9ccc8e.png)

I see three errors in the console. First one:
```
linter-registry.js:145 [Linter] Error running docblock-python TypeError: Cannot read property 'map' of undefined
    at file:///C:/Users/samam/.atom/packages/docblock-python/lib/docblock-python.js:176:38
    at new Promise (<anonymous>)
    at Object.lint (file:///C:/Users/samam/.atom/packages/docblock-python/lib/docblock-python.js:175:14)
    at file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:113:26
    at new Promise (<anonymous>)
    at _loop (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:111:9)
    at LinterRegistry.<anonymous> (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:98:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:178:4)
    at Generator.next (<anonymous>)
    at step (C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:273)
    at C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:443
    at new Promise (<anonymous>)
    at LinterRegistry.<anonymous> (C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:99)
    at file:///C:/Users/samam/.atom/packages/linter/lib/main.js:114:30
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at EditorLinter.lint (file:///C:/Users/samam/.atom/packages/linter/lib/editor-linter.js:52:18)
    at EditorRegistry.createFromTextEditor (file:///C:/Users/samam/.atom/packages/linter/lib/editor-registry.js:47:20)
    at file:///C:/Users/samam/.atom/packages/linter/lib/editor-registry.js:28:14
    at onDidAddTextEditor (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:428476)
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at onDidAddPaneItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:426579)
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at PaneContainer.didAddPaneItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:446715)
    at Pane.addItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:459126)
    at Pane.activateItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:457989)
    at Workspace.open (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:431703)
(anonymous) @ linter-registry.js:145
```

Second one, possibly unrelated:
```
Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:519423)
    at TextEditor.decorateMarker (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:27540)
    at DatatipManager.mountDataTipWithMarker (C:\Users\samam\.atom\packages\atom-ide-datatip\lib\datatip-manager.js:386:12)
    at DatatipManager.showDataTip (C:\Users\samam\.atom\packages\atom-ide-datatip\lib\datatip-manager.js:325:48)
```

Third one:
```
[Linter] Error running docblock-python TypeError: Cannot read property 'map' of undefined
    at file:///C:/Users/samam/.atom/packages/docblock-python/lib/docblock-python.js:176:38
    at new Promise (<anonymous>)
    at Object.lint (file:///C:/Users/samam/.atom/packages/docblock-python/lib/docblock-python.js:175:14)
    at file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:113:26
    at new Promise (<anonymous>)
    at _loop (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:111:9)
    at LinterRegistry.<anonymous> (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:98:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (file:///C:/Users/samam/.atom/packages/linter/lib/linter-registry.js:178:4)
    at Generator.next (<anonymous>)
    at step (C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:273)
    at C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:443
    at new Promise (<anonymous>)
    at LinterRegistry.<anonymous> (C:\Users\samam\.atom\packages\linter\lib\linter-registry.js:9:99)
    at file:///C:/Users/samam/.atom/packages/linter/lib/main.js:114:30
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at EditorLinter.lint (file:///C:/Users/samam/.atom/packages/linter/lib/editor-linter.js:52:18)
    at EditorRegistry.createFromTextEditor (file:///C:/Users/samam/.atom/packages/linter/lib/editor-registry.js:47:20)
    at file:///C:/Users/samam/.atom/packages/linter/lib/editor-registry.js:28:14
    at onDidAddTextEditor (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:428476)
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at onDidAddPaneItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:426579)
    at Function.simpleDispatch (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at PaneContainer.didAddPaneItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:446715)
    at Pane.addItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:459126)
    at Pane.activateItem (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:457989)
    at Workspace.open (C:\Users\samam\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:431703)
```

**Comment by spadarian** [comment]
Hi,

Sorry for the delay. Can you share a minimal example to reproduce the error? I've seen that error before but I can't reproduce it now...

**Comment by samamorgan** [comment]
Sorry, I've been forced to abandon Atom for Python. I grew tired of struggling with the various compatibility issues and bugs with Python extensions.
